export const MOCK_RICETTE = [
  {
    countryId: 'italia',
    recipes: [
      {
        id: 1,
        title: 'Carbonara Classica',
        ingredienti: 'spaghetti, guanciale, uova, pecorino, pepe nero',
        tempoPreparazione: 10,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 15,
        tempoCotturaUnita: 'min',
        porzioni: 4,
        costoPerPersona: 'Basso',
        difficolta: 'Facile',
        preparazione: 'Cuoci la pasta, rosola il guanciale, mescola con uova e pecorino.',
        categoria: 'Primi',
        imageUrl:
          'https://www.giallozafferano.it/images/228-22832/Spaghetti-alla-carbonara_1200x800.jpg',
      },
      {
        id: 2,
        title: 'Parmigiana di Melanzane',
        ingredienti: 'melanzane, pomodoro, mozzarella, parmigiano, basilico',
        tempoPreparazione: 30,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 45,
        tempoCotturaUnita: 'min',
        porzioni: 6,
        costoPerPersona: 'Medio',
        difficolta: 'Media',
        preparazione: 'Friggi le melanzane, stratifica con sugo e formaggi, inforna.',
        categoria: 'Secondi',
        imageUrl:
          'https://www.giallozafferano.it/images/228-22861/Parmigiana-di-melanzane_1200x800.jpg',
      },
      {
        id: 3,
        title: 'Tiramisù',
        ingredienti: 'savoiardi, mascarpone, caffè, cacao, uova, zucchero',
        tempoPreparazione: 20,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 0,
        tempoCotturaUnita: 'min',
        porzioni: 8,
        costoPerPersona: 'Medio',
        difficolta: 'Facile',
        preparazione: 'Prepara la crema al mascarpone, inzuppa i savoiardi nel caffè, stratifica.',
        categoria: 'Dolci',
        imageUrl: 'https://www.giallozafferano.it/images/228-22828/Tiramisu_1200x800.jpg',
      },
      {
        id: 4,
        title: 'Risotto ai Funghi',
        ingredienti: 'riso carnaroli, funghi porcini, brodo vegetale, vino bianco, parmigiano',
        tempoPreparazione: 10,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 25,
        tempoCotturaUnita: 'min',
        porzioni: 4,
        costoPerPersona: 'Alto',
        difficolta: 'Media',
        preparazione: 'Tosta il riso, aggiungi vino e brodo gradualmente, manteca con parmigiano.',
        categoria: 'Primi',
        imageUrl:
          'https://www.giallozafferano.it/images/228-22878/Risotto-ai-funghi-porcini_1200x800.jpg',
      },
      {
        id: 5,
        title: 'Lasagne alla Bolognese',
        ingredienti: 'sfoglia, ragù, besciamella, parmigiano',
        tempoPreparazione: 45,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 40,
        tempoCotturaUnita: 'min',
        porzioni: 8,
        costoPerPersona: 'Medio',
        difficolta: 'Difficile',
        preparazione: 'Prepara ragù e besciamella, stratifica con la sfoglia, inforna.',
        categoria: 'Primi',
        imageUrl:
          'https://www.giallozafferano.it/images/228-22866/Lasagne-alla-Bolognese_1200x800.jpg',
      },
      {
        id: 6,
        title: 'Caprese',
        ingredienti: 'pomodori, mozzarella di bufala, basilico, olio evo',
        tempoPreparazione: 5,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 0,
        tempoCotturaUnita: 'min',
        porzioni: 2,
        costoPerPersona: 'Medio',
        difficolta: 'Facile',
        preparazione: 'Affetta pomodori e mozzarella, condisci con basilico e olio.',
        categoria: 'Antipasti',
        imageUrl: 'https://www.giallozafferano.it/images/228-22846/Caprese_1200x800.jpg',
      },
      {
        id: 7,
        title: 'Amatriciana',
        ingredienti: 'bucatini, guanciale, pomodoro, pecorino, peperoncino',
        tempoPreparazione: 10,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 20,
        tempoCotturaUnita: 'min',
        porzioni: 4,
        costoPerPersona: 'Basso',
        difficolta: 'Facile',
        preparazione: 'Rosola il guanciale, aggiungi il pomodoro, condisci la pasta.',
        categoria: 'Primi',
        imageUrl:
          'https://www.giallozafferano.it/images/228-22844/Bucatini-all-amatriciana_1200x800.jpg',
      },
      {
        id: 8,
        title: 'Ossobuco alla Milanese',
        ingredienti: 'ossobuco, farina, vino bianco, brodo, gremolata',
        tempoPreparazione: 20,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 90,
        tempoCotturaUnita: 'min',
        porzioni: 4,
        costoPerPersona: 'Alto',
        difficolta: 'Media',
        preparazione: "Infarinare e rosolare l'ossobuco, cuocere lentamente con vino e brodo.",
        categoria: 'Secondi',
        imageUrl:
          'https://www.giallozafferano.it/images/228-22892/Ossobuco-alla-milanese_1200x800.jpg',
      },
      {
        id: 9,
        title: 'Panna Cotta',
        ingredienti: 'panna, zucchero, vaniglia, gelatina, frutti di bosco',
        tempoPreparazione: 15,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 5,
        tempoCotturaUnita: 'min',
        porzioni: 6,
        costoPerPersona: 'Basso',
        difficolta: 'Facile',
        preparazione: 'Sciogli la gelatina nella panna calda con zucchero, versa negli stampi.',
        categoria: 'Dolci',
        imageUrl: 'https://www.giallozafferano.it/images/228-22862/Panna-cotta_1200x800.jpg',
      },
      {
        id: 10,
        title: 'Arancini Siciliani',
        ingredienti: 'riso, ragù, piselli, mozzarella, pangrattato',
        tempoPreparazione: 40,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 30,
        tempoCotturaUnita: 'min',
        porzioni: 8,
        costoPerPersona: 'Medio',
        difficolta: 'Difficile',
        preparazione: 'Prepara il riso, forma le palline con ragù interno, impana e friggi.',
        categoria: 'Antipasti',
        imageUrl: 'https://www.giallozafferano.it/images/228-22845/Arancini-di-riso_1200x800.jpg',
      },
    ],
  },
  {
    countryId: 'francia',
    recipes: [
      {
        id: 11,
        title: 'Ratatouille',
        ingredienti: 'melanzane, zucchine, peperoni, pomodori, cipolla, aglio',
        tempoPreparazione: 20,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 40,
        tempoCotturaUnita: 'min',
        porzioni: 4,
        costoPerPersona: 'Basso',
        difficolta: 'Facile',
        preparazione: 'Taglia le verdure, cuoci separatamente, unisci e stufa.',
        categoria: 'Contorni',
      },
      {
        id: 12,
        title: 'Coq au Vin',
        ingredienti: 'pollo, vino rosso, pancetta, funghi, cipollotti, brodo',
        tempoPreparazione: 30,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 1,
        tempoCotturaUnita: 'ora',
        porzioni: 6,
        costoPerPersona: 'Medio',
        difficolta: 'Media',
        preparazione: 'Rosola il pollo, aggiungi vino e verdure, cuoci lentamente.',
        categoria: 'Secondi',
      },
      {
        id: 13,
        title: 'Crème Brûlée',
        ingredienti: 'panna, tuorli, zucchero, vaniglia',
        tempoPreparazione: 15,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 45,
        tempoCotturaUnita: 'min',
        porzioni: 6,
        costoPerPersona: 'Medio',
        difficolta: 'Media',
        preparazione: 'Prepara la crema, cuoci a bagnomaria, caramellizza lo zucchero.',
        categoria: 'Dolci',
      },
      {
        id: 14,
        title: 'Quiche Lorraine',
        ingredienti: 'pasta brisée, pancetta, uova, panna, gruyère',
        tempoPreparazione: 20,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 35,
        tempoCotturaUnita: 'min',
        porzioni: 6,
        costoPerPersona: 'Medio',
        difficolta: 'Facile',
        preparazione: 'Stendi la pasta, riempi con pancetta e crema, inforna.',
        categoria: 'Antipasti',
      },
      {
        id: 15,
        title: 'Bouillabaisse',
        ingredienti: 'pesce misto, gamberi, cozze, pomodoro, zafferano, aglio',
        tempoPreparazione: 30,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 40,
        tempoCotturaUnita: 'min',
        porzioni: 6,
        costoPerPersona: 'Alto',
        difficolta: 'Difficile',
        preparazione: 'Prepara il brodo aromatico, aggiungi il pesce a tempi diversi.',
        categoria: 'Primi',
      },
      {
        id: 16,
        title: 'Tarte Tatin',
        ingredienti: 'mele, pasta sfoglia, burro, zucchero',
        tempoPreparazione: 15,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 30,
        tempoCotturaUnita: 'min',
        porzioni: 8,
        costoPerPersona: 'Basso',
        difficolta: 'Media',
        preparazione: 'Caramellizza le mele, copri con sfoglia, inforna e capovolgi.',
        categoria: 'Dolci',
      },
      {
        id: 17,
        title: "Soupe à l'Oignon",
        ingredienti: 'cipolle, brodo di carne, pane, gruyère, vino bianco',
        tempoPreparazione: 15,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 45,
        tempoCotturaUnita: 'min',
        porzioni: 4,
        costoPerPersona: 'Basso',
        difficolta: 'Facile',
        preparazione: 'Caramellizza le cipolle, aggiungi brodo e vino, gratina con formaggio.',
        categoria: 'Primi',
      },
      {
        id: 18,
        title: 'Boeuf Bourguignon',
        ingredienti: 'manzo, vino rosso, pancetta, carote, cipollotti, funghi',
        tempoPreparazione: 30,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 2.5,
        tempoCotturaUnita: 'ore',
        porzioni: 6,
        costoPerPersona: 'Alto',
        difficolta: 'Difficile',
        preparazione: 'Marina la carne nel vino, rosola e cuoci lentamente con verdure.',
        categoria: 'Secondi',
      },
      {
        id: 19,
        title: 'Croissant',
        ingredienti: 'farina, burro, lievito, latte, zucchero, sale',
        tempoPreparazione: 3,
        tempoPreparazioneUnita: 'ore',
        tempoCottura: 20,
        tempoCotturaUnita: 'min',
        porzioni: 12,
        costoPerPersona: 'Medio',
        difficolta: 'Difficile',
        preparazione: 'Prepara la sfoglia laminata, forma i croissant, lievita e cuoci.',
        categoria: 'Dolci',
      },
      {
        id: 20,
        title: 'Salade Niçoise',
        ingredienti: 'tonno, uova, fagiolini, pomodori, olive, acciughe, lattuga',
        tempoPreparazione: 20,
        tempoPreparazioneUnita: 'min',
        tempoCottura: 10,
        tempoCotturaUnita: 'min',
        porzioni: 4,
        costoPerPersona: 'Medio',
        difficolta: 'Facile',
        preparazione: 'Cuoci uova e fagiolini, assembla con gli altri ingredienti.',
        categoria: 'Antipasti',
      },
    ],
  },
];
